title: Pattrick (Phat) Nguyen
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > 
  MSc. Aalto University - Business Analytics
  <br><br>
  Seeking new internship/trainee opportunities in Data Analytics & Business Intelligence.
  <br><br>
  <a href="https://www.linkedin.com/in/phatnguyen95/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

